### ISSUE TITLE
能否支持阿里ipv6呢

### ISSUE THREAD

**Issue by zjkyz8** [honwen/luci-app-aliddns#12]
用了移动的网络，没有外网IPv4地址，但是有外网IPv6地址，阿里是支持IPv6解析的，插件可否也支持一下呢？

**Comment by honwen** [comment]
Pull requests are always welcome.
--

**Comment by gz19880228** [comment]
Hello there,

I created a pull request adding the IPv6 support. But I'm not a pro coder so my code may be bad.

At least I got IPv6 update working on my NETGEAR R6100 with OpenWrt 19.07, though it's limited to updating the same subdomain.

Also plz note that I didn't test the feature of new DNS record creation. I only tested updating and it's working perfectly on my device for now.

Hope everything's good.

**Comment by honwen** [comment]
PLz help testting https://github.com/honwen/luci-app-aliddns/releases/tag/v20210117

and TKs https://github.com/gz19880228 again
