### ISSUE TITLE
ipv6 internet获取有几处错误

### ISSUE THREAD

**Issue by DaXiongAhey** [honwen/luci-app-aliddns#20]
比如第一个 ipv6.whatismyip.akamai.com，这个获取到的是残缺的。
还有一个ip.sb，他的ipv6域名现在是ipv6.ip.sb。

最好把ip.sb放第一个吧，比较好使。

**Comment by honwen** [comment]
欢迎PR, 没IPv6环境调试

**Comment by chenyg0911** [comment]
IPV6的WAN IP根本就取不到。

**Comment by amazingfate** [comment]
我家是河南联通，ipv6地址在wan_6，ipv4地址在wan，因为脚本默认是两个地址都在一个接口，所以我只能自己改获取ipv6地址的那一行
使用如下命令获取ipv6地址：
```
ip6=`urlencode $(ubus call network.interface.wan_6 status | grep '"address"'|awk 'NR==1{print}'|awk '{print $2}'|sed 's|"||g'|sed 's|,||g')`
```
